# Generated by Django 4.1.7 on 2023-03-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_picture', models.ImageField(blank=True, upload_to='images/%Y/%m', verbose_name='post picture')),
                ('first_name', models.CharField(blank=True, default='Иван Иванович', max_length=120, verbose_name='имя и отчество')),
                ('last_name', models.CharField(blank=True, default='Иванов', max_length=60, verbose_name='фамилия')),
                ('description', models.TextField(default='', max_length=300, verbose_name='описание')),
                ('age', models.PositiveIntegerField(max_length=150, verbose_name='возраст')),
                ('born', models.DateTimeField(verbose_name='дата рождения')),
                ('death', models.DateTimeField(verbose_name='дата смерти')),
            ],
            options={
                'verbose_name': 'human',
                'verbose_name_plural': 'humans',
                'default_related_name': 'humans',
            },
        ),
    ]
