# Generated by Django 4.1.7 on 2023-03-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_human_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='NS',
            field=models.FloatField(default=0.0, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='human',
            name='WE',
            field=models.FloatField(default=0.0, verbose_name='долгота'),
        ),
    ]
